// ===== COMPREHENSIVE MEDICAL DATABASE =====
// Curated from WHO ICD-11, NLEM India, CDSCO drug list

export const CONDITIONS_DB = [
  // GASTRO & LIVER
  { keywords:["gall bladder","gallstone","gall stone","gallbladder","bile duct"], conditions:[{name:"Cholelithiasis (Gallstones)",probability:"High",description:"Hard deposits in gallbladder causing pain in upper right abdomen, nausea, bloating after fatty meals."},{name:"Cholecystitis",probability:"Medium",description:"Inflammation of gallbladder, often from gallstones blocking bile duct. May need surgery."},{name:"Biliary Colic",probability:"Medium",description:"Sudden intense pain when gallstone blocks bile duct. Pain radiates to back/shoulder."}], severity:"Severe", specialist:"Gastroenterologist", actions:["Avoid fatty/fried foods immediately","Ultrasound abdomen is essential","Consult surgeon — may need laparoscopic cholecystectomy","Take antispasmodic for pain relief","⚠️ Go to ER if severe pain with fever/jaundice"] },
  { keywords:["appendix","appendicitis","right lower pain"], conditions:[{name:"Acute Appendicitis",probability:"High",description:"Inflammation of appendix causing sharp pain in lower right abdomen. SURGICAL EMERGENCY."},{name:"Mesenteric Lymphadenitis",probability:"Low",description:"Swollen lymph nodes in abdomen mimicking appendicitis."}], severity:"Critical", specialist:"Surgeon", actions:["⚠️ DO NOT EAT OR DRINK — surgery may be needed","Go to nearest hospital ER immediately","Do NOT take painkillers before diagnosis","CT scan / ultrasound needed urgently"] },
  { keywords:["hernia","inguinal","bulge groin","abdominal bulge"], conditions:[{name:"Inguinal Hernia",probability:"High",description:"Tissue bulging through weak spot in abdominal wall, common in groin area."},{name:"Umbilical Hernia",probability:"Medium",description:"Bulge near navel, common in infants and overweight adults."}], severity:"Moderate", specialist:"Surgeon", actions:["Avoid heavy lifting","Consult surgeon for evaluation","Surgery (hernioplasty) may be needed","Wear abdominal support if advised","⚠️ ER if sudden severe pain (strangulated hernia)"] },
  { keywords:["jaundice","yellow skin","yellow eyes","bilirubin","hepatitis"], conditions:[{name:"Hepatitis (Viral)",probability:"High",description:"Liver inflammation from Hepatitis A/B/C/E virus. Common in India."},{name:"Obstructive Jaundice",probability:"Medium",description:"Bile duct blockage from gallstones or tumor causing yellowing."},{name:"Alcoholic Liver Disease",probability:"Low",description:"Liver damage from chronic alcohol use."}], severity:"Severe", specialist:"Gastroenterologist", actions:["Get liver function tests (LFT) immediately","Complete bed rest","Drink plenty of fluids, avoid alcohol completely","Get Hepatitis virus panel test","Consult gastroenterologist/hepatologist"] },
  { keywords:["acid reflux","gerd","heartburn","acidity","burning chest","sour taste"], conditions:[{name:"GERD (Acid Reflux)",probability:"High",description:"Stomach acid flows back into esophagus causing burning sensation."},{name:"Peptic Ulcer",probability:"Medium",description:"Sores in stomach/duodenum from H.pylori or NSAIDs."},{name:"Gastritis",probability:"Medium",description:"Stomach lining inflammation from spicy food, stress, or infection."}], severity:"Mild", specialist:"Gastroenterologist", actions:["Avoid spicy, oily, acidic foods","Don't lie down after eating (wait 2-3 hrs)","Take antacid (Pantoprazole/Omeprazole)","Eat small frequent meals","Get H.pylori test if persistent"] },
  { keywords:["constipation","hard stool","no bowel movement","bloating gas"], conditions:[{name:"Functional Constipation",probability:"High",description:"Infrequent hard stools from low fiber, dehydration, sedentary lifestyle."},{name:"Irritable Bowel Syndrome (IBS-C)",probability:"Medium",description:"Chronic constipation with abdominal pain and bloating."}], severity:"Mild", specialist:"Gastroenterologist", actions:["Increase fiber (fruits, vegetables, whole grains)","Drink 3-4 liters water daily","Exercise 30 minutes daily","Take Isabgol (psyllium husk) at night","See doctor if blood in stool or >2 weeks"] },
  { keywords:["piles","hemorrhoids","bleeding stool","rectal bleeding","anal pain"], conditions:[{name:"Hemorrhoids (Piles)",probability:"High",description:"Swollen veins in rectum/anus causing pain, itching, bleeding."},{name:"Anal Fissure",probability:"Medium",description:"Small tear in anal lining causing sharp pain during bowel movement."}], severity:"Moderate", specialist:"Surgeon", actions:["Increase fiber and water intake","Sitz bath (warm water soak) 3 times daily","Apply topical hemorrhoid cream","Avoid straining during bowel movement","Consult surgeon if severe or persistent bleeding"] },
  { keywords:["liver","fatty liver","liver damage","cirrhosis"], conditions:[{name:"Non-Alcoholic Fatty Liver (NAFLD)",probability:"High",description:"Fat buildup in liver, very common in India. Often linked to obesity/diabetes."},{name:"Cirrhosis",probability:"Low",description:"Advanced liver scarring from chronic damage. Serious condition."}], severity:"Moderate", specialist:"Gastroenterologist", actions:["Complete alcohol abstinence","Lose weight if overweight","Low-fat, high-fiber diet","Get LFT and liver ultrasound","Regular follow-up with hepatologist"] },

  // CARDIOLOGY
  { keywords:["chest pain","heart pain","angina","heart attack","cardiac"], conditions:[{name:"Angina Pectoris",probability:"High",description:"Chest pain from reduced blood flow to heart. Warning sign of heart disease."},{name:"Myocardial Infarction (Heart Attack)",probability:"Medium",description:"CRITICAL: Complete blockage of coronary artery. Pain radiates to arm/jaw."},{name:"Costochondritis",probability:"Low",description:"Chest wall inflammation mimicking heart pain. Harmless but painful."}], severity:"Critical", specialist:"Cardiologist", actions:["⚠️ CALL 108/112 IMMEDIATELY if severe","Chew aspirin 325mg if available","Sit upright, stay calm","ECG needed within 10 minutes","Do NOT ignore — every minute counts"] },
  { keywords:["blood pressure","bp high","hypertension","bp low","hypotension"], conditions:[{name:"Essential Hypertension",probability:"High",description:"Persistently elevated BP >140/90. Leading cause of heart disease and stroke in India."},{name:"Secondary Hypertension",probability:"Low",description:"High BP caused by kidney disease, thyroid, or other conditions."}], severity:"Moderate", specialist:"Cardiologist", actions:["Reduce salt intake (<5g/day)","Exercise 30 min daily","Maintain healthy weight","Take BP medication regularly if prescribed","Monitor BP at home twice daily"] },
  { keywords:["palpitation","heart racing","irregular heartbeat","heart flutter","arrhythmia"], conditions:[{name:"Cardiac Arrhythmia",probability:"Medium",description:"Irregular heartbeat — can be harmless or serious depending on type."},{name:"Anxiety/Panic Attack",probability:"High",description:"Stress and anxiety commonly cause heart racing and palpitations."},{name:"Thyroid Disorder",probability:"Medium",description:"Hyperthyroidism often causes rapid heartbeat."}], severity:"Moderate", specialist:"Cardiologist", actions:["Deep breathing exercises","Avoid caffeine and alcohol","Get ECG and thyroid test (TSH)","Check electrolytes (potassium, magnesium)","⚠️ ER if accompanied by chest pain or fainting"] },
  { keywords:["cholesterol","lipid","triglycerides","ldl high"], conditions:[{name:"Dyslipidemia (High Cholesterol)",probability:"High",description:"Elevated LDL/triglycerides increasing heart disease risk. Very common in Indian diet."}], severity:"Moderate", specialist:"Cardiologist", actions:["Low-fat, high-fiber diet","Reduce fried foods and sweets","Exercise 45 min daily","Get lipid profile test","May need statin medication (Atorvastatin)"] },

  // NEUROLOGY
  { keywords:["headache","head pain","migraine","throbbing head","head heavy"], conditions:[{name:"Tension Headache",probability:"High",description:"Band-like pressure around head. Most common type from stress/screen time."},{name:"Migraine",probability:"Medium",description:"Intense throbbing pain, usually one-sided. Nausea, light sensitivity."},{name:"Sinusitis Headache",probability:"Medium",description:"Frontal headache with nasal congestion from sinus inflammation."},{name:"Cluster Headache",probability:"Low",description:"Severe pain around one eye. Occurs in clusters over weeks."}], severity:"Mild", specialist:"Neurologist", actions:["Rest in dark, quiet room","Stay hydrated","Paracetamol/Ibuprofen for relief","Apply cold compress on forehead","See neurologist if >3 episodes/week or sudden severe onset"] },
  { keywords:["seizure","epilepsy","fits","convulsion","unconscious fit"], conditions:[{name:"Epilepsy",probability:"High",description:"Neurological disorder causing recurrent seizures. Needs long-term medication."},{name:"Febrile Seizure",probability:"Medium",description:"Seizure triggered by high fever, common in young children."}], severity:"Severe", specialist:"Neurologist", actions:["During seizure: turn person on side, clear area","Do NOT put anything in mouth","Time the seizure duration","⚠️ Call ambulance if >5 minutes","Get EEG and MRI brain done"] },
  { keywords:["stroke","paralysis","face drooping","speech slurred","arm weakness","numbness one side"], conditions:[{name:"Stroke (Cerebrovascular Accident)",probability:"High",description:"CRITICAL: Brain blood supply disrupted. Use FAST test: Face-Arms-Speech-Time."}], severity:"Critical", specialist:"Neurologist", actions:["⚠️ CALL 108/112 IMMEDIATELY — time is brain","Note exact time symptoms started","Do NOT give food or water","Keep person lying with head elevated","Get to stroke-ready hospital within 4.5 hours"] },
  { keywords:["vertigo","dizziness","room spinning","balance problem","lightheaded"], conditions:[{name:"BPPV (Benign Positional Vertigo)",probability:"High",description:"Inner ear crystals displaced causing brief spinning with head movement."},{name:"Meniere's Disease",probability:"Low",description:"Inner ear disorder with vertigo, hearing loss, tinnitus."},{name:"Labyrinthitis",probability:"Medium",description:"Inner ear infection causing vertigo, nausea, hearing changes."}], severity:"Moderate", specialist:"ENT Specialist", actions:["Sit or lie down when dizzy","Avoid sudden head movements","Epley maneuver for BPPV","Stay hydrated","See ENT if recurrent or with hearing loss"] },
  { keywords:["memory loss","forgetful","alzheimer","dementia","confusion elderly"], conditions:[{name:"Age-Related Cognitive Decline",probability:"High",description:"Mild memory changes with aging, usually not progressive."},{name:"Dementia/Alzheimer's",probability:"Medium",description:"Progressive brain disorder affecting memory, thinking, behavior."}], severity:"Moderate", specialist:"Neurologist", actions:["Mental exercises (puzzles, reading)","Social engagement","Regular physical exercise","Balanced diet rich in omega-3","Neurologist evaluation for proper assessment"] },

  // RESPIRATORY
  { keywords:["cough","cold","runny nose","sneezing","nasal congestion","sore throat","throat pain","flu"], conditions:[{name:"Common Cold (URTI)",probability:"High",description:"Viral upper respiratory infection. Self-limiting in 5-7 days."},{name:"Influenza (Flu)",probability:"Medium",description:"More severe viral infection with high fever, body ache."},{name:"Allergic Rhinitis",probability:"Medium",description:"Allergic reaction causing sneezing, runny nose, itchy eyes."},{name:"COVID-19",probability:"Low",description:"Coronavirus infection. Get tested if fever with loss of smell/taste."}], severity:"Mild", specialist:"General Physician", actions:["Rest and hydration","Warm salt water gargle","Steam inhalation 3 times daily","Honey-ginger-tulsi tea for throat","See doctor if fever >3 days or breathing difficulty"] },
  { keywords:["asthma","wheezing","breathless","breathing difficulty","shortness of breath","dyspnea"], conditions:[{name:"Bronchial Asthma",probability:"High",description:"Chronic airway inflammation with wheezing, cough, breathlessness."},{name:"COPD",probability:"Medium",description:"Chronic lung disease mainly in smokers. Progressive breathlessness."},{name:"Pneumonia",probability:"Medium",description:"Lung infection with fever, cough with sputum, breathing difficulty."},{name:"Pulmonary Embolism",probability:"Low",description:"Blood clot in lung. EMERGENCY if sudden breathlessness with chest pain."}], severity:"Severe", specialist:"Pulmonologist", actions:["Sit upright to ease breathing","Use rescue inhaler (Salbutamol) if prescribed","Avoid dust, smoke, allergens","⚠️ ER if severe breathlessness or blue lips","Get chest X-ray, PFT, SpO2 check"] },
  { keywords:["tuberculosis","tb","cough blood","night sweats","weight loss cough","persistent cough"], conditions:[{name:"Pulmonary Tuberculosis",probability:"High",description:"TB is very common in India. Cough >2 weeks with fever, weight loss, night sweats."},{name:"Lung Cancer",probability:"Low",description:"Persistent cough with blood, weight loss in smokers >45 yrs."}], severity:"Severe", specialist:"Pulmonologist", actions:["Get sputum test (AFB/GeneXpert) immediately","Chest X-ray essential","Isolate to prevent spread","TB is fully curable with 6-month DOTS treatment","Contact local DOTS center for free treatment"] },

  // ORTHOPEDICS
  { keywords:["joint pain","arthritis","knee pain","swollen joint","stiffness morning"], conditions:[{name:"Osteoarthritis",probability:"High",description:"Wear-and-tear of joint cartilage. Very common after age 50."},{name:"Rheumatoid Arthritis",probability:"Medium",description:"Autoimmune joint inflammation causing morning stiffness, swelling."},{name:"Gout",probability:"Medium",description:"Uric acid crystal deposits in joints. Sudden severe pain, often big toe."}], severity:"Moderate", specialist:"Orthopedic", actions:["Hot/cold compress on affected joint","Gentle range-of-motion exercises","Maintain healthy weight","Get X-ray and blood tests (RA factor, uric acid)","Avoid prolonged standing/sitting"] },
  { keywords:["back pain","spine","disc","sciatica","lower back","lumbar"], conditions:[{name:"Lumbar Spondylosis",probability:"High",description:"Age-related spine wear causing lower back pain and stiffness."},{name:"Herniated Disc (Slip Disc)",probability:"Medium",description:"Disc between vertebrae pushes out, pressing on nerve."},{name:"Sciatica",probability:"Medium",description:"Nerve pain radiating from lower back down the leg."}], severity:"Moderate", specialist:"Orthopedic", actions:["Avoid sitting for long periods","Sleep on firm mattress","Back strengthening exercises","Hot compress for muscle spasm","MRI spine if symptoms persist >4 weeks"] },
  { keywords:["fracture","broken bone","bone crack","fall injury","swelling after fall"], conditions:[{name:"Bone Fracture",probability:"High",description:"Bone break from trauma/fall. X-ray essential for diagnosis."},{name:"Soft Tissue Injury",probability:"Medium",description:"Muscle/ligament damage without bone break."}], severity:"Severe", specialist:"Orthopedic", actions:["Immobilize the injured area","Apply ice pack (20 min on, 20 off)","⚠️ Go to ER for X-ray immediately","Do NOT try to set the bone yourself","Elevate the injured limb"] },
  { keywords:["vitamin d","calcium deficiency","weak bones","osteoporosis","bone pain"], conditions:[{name:"Vitamin D Deficiency",probability:"High",description:"Extremely common in India (80%+). Causes bone pain, fatigue, muscle weakness."},{name:"Osteoporosis",probability:"Medium",description:"Weak, brittle bones prone to fractures. Common in post-menopausal women."}], severity:"Mild", specialist:"Orthopedic", actions:["Get Vitamin D and Calcium blood test","30 min sunlight exposure daily","Vitamin D3 60K sachets weekly (as prescribed)","Calcium-rich diet (milk, curd, ragi)","Weight-bearing exercises for bone health"] },

  // DERMATOLOGY
  { keywords:["skin rash","itching","redness","eczema","dermatitis","hives","urticaria"], conditions:[{name:"Eczema/Dermatitis",probability:"High",description:"Chronic skin inflammation with red, itchy, dry patches."},{name:"Urticaria (Hives)",probability:"Medium",description:"Raised itchy welts from allergic reaction."},{name:"Contact Dermatitis",probability:"Medium",description:"Skin reaction from contact with irritant/allergen."}], severity:"Mild", specialist:"Dermatologist", actions:["Moisturize affected area frequently","Avoid known allergens/irritants","Antihistamine (Cetirizine) for itch","Calamine lotion for relief","See dermatologist if spreading or infected"] },
  { keywords:["acne","pimples","face spots","blackheads","oily skin"], conditions:[{name:"Acne Vulgaris",probability:"High",description:"Blocked pores causing pimples, blackheads, whiteheads on face/back."},{name:"Hormonal Acne",probability:"Medium",description:"Acne related to hormonal changes, common in teens and women with PCOS."}], severity:"Mild", specialist:"Dermatologist", actions:["Wash face twice daily with gentle cleanser","Don't pop/squeeze pimples","Use non-comedogenic products","Benzoyl peroxide or salicylic acid topically","See dermatologist for severe/scarring acne"] },
  { keywords:["fungal infection","ringworm","fungus","jock itch","athlete foot","white patches skin"], conditions:[{name:"Dermatophytosis (Ringworm)",probability:"High",description:"Fungal skin infection causing circular, red, itchy patches. Very common in India."},{name:"Tinea Versicolor",probability:"Medium",description:"Yeast infection causing light/dark skin patches."},{name:"Candidiasis",probability:"Medium",description:"Yeast infection in skin folds, groin, or mouth."}], severity:"Mild", specialist:"Dermatologist", actions:["Keep affected area clean and dry","Apply antifungal cream (Clotrimazole) twice daily","Wear loose cotton clothing","Don't share towels/clothing","Complete full 4-week course even if better"] },
  { keywords:["psoriasis","scaly skin","silver scales","dry patches thick"], conditions:[{name:"Psoriasis",probability:"High",description:"Autoimmune condition causing thick, scaly, silvery skin patches. Chronic but manageable."}], severity:"Moderate", specialist:"Dermatologist", actions:["Moisturize heavily","Avoid skin injury and stress","Topical steroids as prescribed","Phototherapy may help","Long-term dermatologist management needed"] },
  { keywords:["hair loss","baldness","hair fall","alopecia","thinning hair"], conditions:[{name:"Androgenetic Alopecia (Pattern Baldness)",probability:"High",description:"Genetic hair loss, most common cause in men and women."},{name:"Alopecia Areata",probability:"Medium",description:"Autoimmune patchy hair loss. Usually reversible."},{name:"Telogen Effluvium",probability:"Medium",description:"Temporary hair shedding from stress, illness, or nutritional deficiency."}], severity:"Mild", specialist:"Dermatologist", actions:["Check iron, thyroid, Vitamin D levels","Balanced diet with protein","Minoxidil topically if prescribed","Avoid tight hairstyles and heat","PRP therapy under dermatologist guidance"] },

  // UROLOGY & NEPHROLOGY
  { keywords:["uti","urinary infection","burning urination","urine pain","frequent urination"], conditions:[{name:"Urinary Tract Infection (UTI)",probability:"High",description:"Bacterial infection in bladder/urethra. Very common in women."},{name:"Urethritis",probability:"Medium",description:"Inflammation of urethra from infection or irritation."}], severity:"Moderate", specialist:"Urologist", actions:["Drink 3-4 liters water daily","Urinate frequently, don't hold","Get urine routine and culture test","Cranberry juice may help","Antibiotic course needed — see doctor"] },
  { keywords:["kidney stone","renal calculi","kidney pain","flank pain","stone urine"], conditions:[{name:"Renal Calculi (Kidney Stones)",probability:"High",description:"Hard mineral deposits in kidneys causing severe pain, blood in urine."},{name:"Renal Colic",probability:"High",description:"Intense cramping pain from stone passing through ureter."}], severity:"Severe", specialist:"Urologist", actions:["Drink massive amounts of water (4+ liters/day)","Pain relief (Diclofenac injection)","Get CT KUB or ultrasound","Stones <5mm may pass naturally","⚠️ ER if fever with stone pain (infection risk)"] },

  // ENDOCRINOLOGY
  { keywords:["diabetes","sugar high","blood sugar","insulin","hba1c","diabetic"], conditions:[{name:"Type 2 Diabetes Mellitus",probability:"High",description:"Body can't use insulin properly. Very common in India (77M+ cases)."},{name:"Type 1 Diabetes",probability:"Low",description:"Autoimmune destruction of insulin-producing cells. Usually young onset."},{name:"Pre-diabetes",probability:"Medium",description:"Blood sugar higher than normal but not diabetic yet. Reversible!"}], severity:"Moderate", specialist:"Endocrinologist", actions:["Get fasting blood sugar and HbA1c test","Reduce sugar, refined carbs, rice portions","Exercise 45 min daily","Monitor blood sugar regularly","Take medications as prescribed — don't skip"] },
  { keywords:["thyroid","goiter","weight gain fatigue","hypothyroid","hyperthyroid","tsh"], conditions:[{name:"Hypothyroidism",probability:"High",description:"Underactive thyroid causing weight gain, fatigue, cold sensitivity. Very common in Indian women."},{name:"Hyperthyroidism",probability:"Medium",description:"Overactive thyroid causing weight loss, anxiety, rapid heartbeat."},{name:"Thyroid Nodule",probability:"Low",description:"Lump in thyroid gland. Usually benign but needs evaluation."}], severity:"Moderate", specialist:"Endocrinologist", actions:["Get TSH, T3, T4 blood test","Thyroid ultrasound if nodule felt","Take Levothyroxine empty stomach if hypo","Regular 6-monthly thyroid monitoring","Avoid excess iodine and soy"] },
  { keywords:["pcos","irregular period","facial hair female","ovarian cyst","polycystic"], conditions:[{name:"PCOS (Polycystic Ovary Syndrome)",probability:"High",description:"Hormonal disorder in women causing irregular periods, acne, weight gain, excess hair."}], severity:"Moderate", specialist:"Gynecologist", actions:["Maintain healthy weight","Regular exercise crucial","Low-carb, high-protein diet","Get hormonal panel and pelvic ultrasound","Metformin may be prescribed for insulin resistance"] },

  // OPHTHALMOLOGY
  { keywords:["eye pain","blurry vision","red eye","watery eyes","conjunctivitis","specs","glasses"], conditions:[{name:"Refractive Error (Myopia/Hypermetropia)",probability:"High",description:"Need for corrective lenses. Very common with increased screen time."},{name:"Conjunctivitis",probability:"Medium",description:"Eye infection/allergy causing redness, watering, discharge."},{name:"Dry Eye Syndrome",probability:"Medium",description:"Insufficient tears causing burning, gritty feeling in eyes."},{name:"Glaucoma",probability:"Low",description:"Increased eye pressure damaging optic nerve. Silent vision thief."}], severity:"Mild", specialist:"Ophthalmologist", actions:["Follow 20-20-20 rule (every 20 min, look 20 ft away, 20 sec)","Don't rub eyes","Lubricant eye drops for dryness","Reduce screen brightness and use night mode","Annual eye checkup after age 40"] },
  { keywords:["cataract","cloudy vision","night vision poor","lens opacity"], conditions:[{name:"Cataract",probability:"High",description:"Clouding of eye lens causing blurry vision. Common after age 50."}], severity:"Moderate", specialist:"Ophthalmologist", actions:["Use anti-glare glasses","Cataract surgery is safe and effective","Don't delay surgery if vision affected","Free surgery available at government hospitals","Protect eyes from UV with sunglasses"] },

  // DENTISTRY
  { keywords:["tooth pain","toothache","cavity","dental","gum bleeding","wisdom tooth","swollen gums"], conditions:[{name:"Dental Caries (Cavity)",probability:"High",description:"Tooth decay causing sensitivity and pain."},{name:"Gingivitis/Periodontitis",probability:"Medium",description:"Gum disease causing bleeding, swelling, bad breath."},{name:"Wisdom Tooth Impaction",probability:"Medium",description:"Partially erupted wisdom tooth causing pain and swelling."},{name:"Dental Abscess",probability:"Low",description:"Bacterial infection forming pus near tooth root. Needs antibiotics."}], severity:"Moderate", specialist:"Dentist", actions:["Warm salt water rinse 3 times daily","OTC pain reliever (Ibuprofen)","Brush twice daily with soft toothbrush","Floss daily","Visit dentist — don't delay!"] },

  // PSYCHIATRY
  { keywords:["anxiety","panic attack","stress","nervousness","worry","fear","phobia"], conditions:[{name:"Generalized Anxiety Disorder (GAD)",probability:"High",description:"Persistent excessive worry about everyday things. Very treatable."},{name:"Panic Disorder",probability:"Medium",description:"Sudden episodes of intense fear with physical symptoms."},{name:"Social Anxiety",probability:"Medium",description:"Extreme fear of social situations and being judged."}], severity:"Moderate", specialist:"Psychiatrist", actions:["Deep breathing exercises (4-7-8 technique)","Regular exercise — natural anxiety reducer","Limit caffeine and alcohol","Cognitive Behavioral Therapy (CBT) very effective","It's okay to seek help — no stigma in mental health"] },
  { keywords:["depression","sad","hopeless","no energy","sleep problem","insomnia","suicidal","self harm"], conditions:[{name:"Major Depressive Disorder",probability:"High",description:"Persistent sadness, loss of interest, fatigue. A medical condition, not weakness."},{name:"Bipolar Disorder",probability:"Low",description:"Mood swings between depression and mania."}], severity:"Severe", specialist:"Psychiatrist", actions:["Talk to someone you trust","iCall helpline: 022-25521111","Vandrevala Foundation: 1860-2662-345","Regular sleep, exercise, social connection","Professional help makes a HUGE difference — please reach out"] },

  // ENT
  { keywords:["ear pain","hearing loss","ear infection","tinnitus","ringing ear","ear discharge"], conditions:[{name:"Otitis Media (Middle Ear Infection)",probability:"High",description:"Ear infection causing pain, fever, possible discharge."},{name:"Tinnitus",probability:"Medium",description:"Ringing/buzzing in ears from noise exposure or age."},{name:"Wax Impaction",probability:"High",description:"Earwax buildup causing muffled hearing."}], severity:"Mild", specialist:"ENT Specialist", actions:["Do NOT insert objects in ear","Warm compress on affected ear","OTC ear drops for wax","Avoid loud music/headphones >60% volume","See ENT if discharge, hearing loss, or persistent ringing"] },
  { keywords:["sinus","sinusitis","facial pain","nose block","post nasal drip"], conditions:[{name:"Acute Sinusitis",probability:"High",description:"Inflammation of sinuses causing facial pain, nasal congestion, headache."},{name:"Chronic Sinusitis",probability:"Medium",description:"Sinus inflammation lasting >12 weeks despite treatment."},{name:"Nasal Polyps",probability:"Low",description:"Soft growths in nasal passages causing chronic congestion."}], severity:"Mild", specialist:"ENT Specialist", actions:["Steam inhalation 3-4 times daily","Saline nasal spray/Jal Neti","Avoid allergens and pollution","Decongestant (max 3 days)","See ENT if symptoms >10 days"] },

  // GYNECOLOGY
  { keywords:["pregnancy","pregnant","missed period","morning sickness","positive test"], conditions:[{name:"Early Pregnancy",probability:"High",description:"Missed period with nausea and fatigue. Confirm with blood beta-hCG test."}], severity:"Moderate", specialist:"Gynecologist", actions:["Take home pregnancy test","Start Folic Acid 5mg daily immediately","Avoid alcohol, smoking, raw food","Book appointment with OB-GYN","First ultrasound at 6-8 weeks"] },
  { keywords:["period pain","dysmenorrhea","heavy period","menstrual cramp","irregular cycle"], conditions:[{name:"Dysmenorrhea (Period Pain)",probability:"High",description:"Menstrual cramps — very common, usually manageable."},{name:"Endometriosis",probability:"Medium",description:"Uterine tissue growing outside uterus causing severe pain."},{name:"Uterine Fibroids",probability:"Medium",description:"Non-cancerous uterine growths causing heavy, painful periods."}], severity:"Moderate", specialist:"Gynecologist", actions:["Hot water bottle on lower abdomen","Ibuprofen/Mefenamic Acid for pain","Light exercise helps reduce cramps","Track your cycle in an app","See gynecologist if pain is debilitating"] },

  // PEDIATRICS
  { keywords:["child fever","baby sick","infant cry","child vomiting","child diarrhea","child rash"], conditions:[{name:"Viral Fever (Pediatric)",probability:"High",description:"Most common cause of childhood fever. Usually resolves in 3-5 days."},{name:"Hand-Foot-Mouth Disease",probability:"Medium",description:"Viral illness common in children with mouth sores and rash."},{name:"Rotavirus Gastroenteritis",probability:"Medium",description:"Viral diarrhea common in young children. Dehydration risk."}], severity:"Moderate", specialist:"Pediatrician", actions:["Give ORS for hydration — critical","Paracetamol drops for fever (weight-based dosing)","Continue breastfeeding if infant","⚠️ ER if baby <3 months with fever","Watch for signs: sunken eyes, no tears, no urine >6hrs"] },

  // INFECTIOUS DISEASES (common in India)
  { keywords:["dengue","platelet low","high fever body pain","mosquito bite fever"], conditions:[{name:"Dengue Fever",probability:"High",description:"Mosquito-borne viral disease with high fever, severe body pain, low platelets."},{name:"Chikungunya",probability:"Medium",description:"Mosquito-borne virus causing fever and severe joint pain."}], severity:"Severe", specialist:"General Physician", actions:["Complete bed rest","Paracetamol ONLY — no Ibuprofen/Aspirin (bleeding risk!)","Drink papaya leaf juice (may help platelets)","Get CBC daily to monitor platelets","⚠️ Hospital if platelets <50,000 or bleeding signs"] },
  { keywords:["malaria","cyclic fever","chills sweating","fever every 2 days","rigor"], conditions:[{name:"Malaria (P. vivax / P. falciparum)",probability:"High",description:"Mosquito-borne parasite causing cyclic fever with chills. P. falciparum can be fatal."}], severity:"Severe", specialist:"General Physician", actions:["Get rapid malaria test and blood smear","Antimalarial treatment essential","Complete full medication course","Use mosquito nets and repellents","⚠️ Hospital if altered consciousness or severe (falciparum)"] },
  { keywords:["typhoid","enteric fever","prolonged fever","abdominal pain fever","widal"], conditions:[{name:"Typhoid Fever",probability:"High",description:"Bacterial infection from contaminated food/water. Common in India."}], severity:"Severe", specialist:"General Physician", actions:["Blood culture and Widal test","Antibiotic course essential (Azithromycin/Ceftriaxone)","Soft bland diet","Boil drinking water","Complete 14-day antibiotic course even if better"] },

  // GENERAL
  { keywords:["fever","temperature","hot body","burning body","chills"], conditions:[{name:"Viral Fever",probability:"High",description:"Most common cause of fever. Self-limiting in 3-5 days."},{name:"Bacterial Infection",probability:"Medium",description:"May need antibiotics if high-grade or persistent fever."},{name:"COVID-19",probability:"Low",description:"Get tested if accompanied by loss of smell/taste or respiratory symptoms."}], severity:"Moderate", specialist:"General Physician", actions:["Paracetamol 500mg every 6 hours","Cold sponging for high fever","Plenty of fluids and rest","Monitor temperature every 4 hours","Doctor visit if fever >3 days or >103°F"] },
  { keywords:["fatigue","tiredness","weakness","no energy","lethargy","exhaustion"], conditions:[{name:"Iron Deficiency Anemia",probability:"High",description:"Low hemoglobin from iron deficiency. Very common in Indian women."},{name:"Vitamin B12 Deficiency",probability:"Medium",description:"Common in vegetarians causing fatigue, tingling, weakness."},{name:"Hypothyroidism",probability:"Medium",description:"Underactive thyroid causing fatigue, weight gain, cold sensitivity."},{name:"Diabetes",probability:"Low",description:"Uncontrolled blood sugar can cause persistent fatigue."}], severity:"Mild", specialist:"General Physician", actions:["Get CBC, iron, B12, thyroid, sugar tests","Iron-rich foods (spinach, jaggery, dates)","B12 supplement if vegetarian","Regular sleep schedule (7-8 hours)","Exercise improves energy levels"] },
  { keywords:["weight gain","obesity","overweight","belly fat","bmi high"], conditions:[{name:"Obesity",probability:"High",description:"Excess body fat increasing risk of diabetes, heart disease, joint problems."},{name:"Hypothyroidism",probability:"Medium",description:"Underactive thyroid is a common treatable cause of weight gain."},{name:"PCOS",probability:"Medium",description:"In women, PCOS causes weight gain with hormonal imbalance."}], severity:"Moderate", specialist:"Endocrinologist", actions:["Thyroid test (TSH) to rule out hypothyroidism","Reduce portions and processed foods","30-45 min exercise daily — walking is great","Track calories and macros","Consult dietitian for personalized meal plan"] },
  { keywords:["allergy","allergic reaction","swelling face","breathing difficulty allergy","anaphylaxis"], conditions:[{name:"Allergic Reaction",probability:"High",description:"Immune response to allergen causing rash, swelling, breathing issues."},{name:"Anaphylaxis",probability:"Low",description:"SEVERE: Life-threatening allergic reaction. EMERGENCY."}], severity:"Severe", specialist:"Allergist", actions:["Antihistamine (Cetirizine/Levocetirizine) immediately","⚠️ CALL 108 if throat swelling or breathing difficulty","Note what triggered the reaction","Epinephrine auto-injector if prescribed","Get allergy testing done to identify triggers"] },
];
